image: node:latest

stages:
    - deploy

deploy:
    stage: deploy
    before_script:
        - apt-get update -qq && apt-get install -y -qq sshpass rsync
        - 'which ssh-agent || (apt-get install -y -qq openssh-client)'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts    
    script:
        - ./CI/deploy.sh
    only:
        - dev