name: Back-end DEV CD

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:  
  deploy:
    uses: ReliefApplications/oort-backend/.github/workflows/deploy.yml@dev
    with:
      environment: OORT_DEV
